{
  "openapi": "3.0.1",
  "info": {
    "title": "CarRentalMarketplace",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/search": {
      "get": {
        "summary": "Search",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "pickup_store_id",
            "in": "query",
            "description": "",
            "required": true,
            "example": "GRU",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dropoff_store_id",
            "in": "query",
            "description": "",
            "required": true,
            "example": "CEN",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pickup_datetime",
            "in": "query",
            "description": "",
            "required": true,
            "example": "2026-01-13T21:30",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dropoff_datetime",
            "in": "query",
            "description": "",
            "required": true,
            "example": "2026-02-11T22:00",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "company",
            "in": "query",
            "description": "",
            "required": false,
            "example": "LOCALIZA",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "search_id": {
                      "type": "string"
                    },
                    "rental_days": {
                      "type": "integer"
                    },
                    "currency": {
                      "type": "string"
                    },
                    "available_groups": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "group_code": {
                            "type": "string"
                          },
                          "category": {
                            "type": "string"
                          },
                          "example_vehicle": {
                            "type": "string"
                          },
                          "features": {
                            "type": "object",
                            "properties": {
                              "seats": {
                                "type": "integer"
                              },
                              "doors": {
                                "type": "integer"
                              },
                              "transmission": {
                                "type": "string"
                              },
                              "air_conditioning": {
                                "type": "boolean"
                              },
                              "large_bags": {
                                "type": "integer"
                              },
                              "small_bags": {
                                "type": "integer"
                              }
                            },
                            "required": [
                              "seats",
                              "doors",
                              "transmission",
                              "air_conditioning",
                              "large_bags",
                              "small_bags"
                            ]
                          },
                          "pricing": {
                            "type": "object",
                            "properties": {
                              "daily_base_rate": {
                                "type": "integer"
                              },
                              "estimated_total_base": {
                                "type": "integer"
                              }
                            },
                            "required": [
                              "daily_base_rate",
                              "estimated_total_base"
                            ]
                          }
                        },
                        "required": [
                          "group_code",
                          "category",
                          "example_vehicle",
                          "features",
                          "pricing"
                        ]
                      }
                    }
                  },
                  "required": [
                    "search_id",
                    "rental_days",
                    "currency",
                    "available_groups"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/extras": {
      "get": {
        "summary": "Extras",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "pickup_store_id",
            "in": "query",
            "description": "",
            "required": false,
            "example": "GRU",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "group_code",
            "in": "query",
            "description": "",
            "required": false,
            "example": "ECON",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pickup_datetime",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2026-01-13T21:30",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dropoff_datetime",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2026-02-11T22:00",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "currency": {
                      "type": "string"
                    },
                    "protections": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "code": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "price": {
                            "type": "integer"
                          },
                          "recommended": {
                            "type": "boolean"
                          }
                        },
                        "required": [
                          "code",
                          "name",
                          "description",
                          "type",
                          "price",
                          "recommended"
                        ]
                      }
                    },
                    "optionals": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "code": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          },
                          "type": {
                            "type": "string"
                          },
                          "price": {
                            "type": "integer"
                          },
                          "max_quantity": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "code",
                          "name",
                          "description",
                          "type",
                          "price",
                          "max_quantity"
                        ]
                      }
                    }
                  },
                  "required": [
                    "currency",
                    "protections",
                    "optionals"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/quote": {
      "post": {
        "summary": "Quote",
        "deprecated": false,
        "description": "## Gerar Cotação (Quote)\n`POST /quote`\n\nEste endpoint recebe os detalhes da pesquisa e as seleções do usuário (adicionais e proteções) para calcular o preço final exato. Ele retorna um detalhamento dos valores e um `quote_id` temporário (hash) que \"trava\" o preço por um curto período (ex: 15 minutos) para ser usado na etapa de reserva (booking).\n\n### Corpo da Requisição (Request Body)\nO payload aceita dados da locação, perfil simplificado do motorista e preferências.\n\n**Exemplo de Requisição:**\n```json\n{\n  \"rental_details\": {\n    \"supplier_id\": \"localiza\",\n    \"pickup_store_id\": \"GRU\",\n    \"dropoff_store_id\": \"CEN\",\n    \"pickup_datetime\": \"2026-01-13T21:30:00Z\",\n    \"dropoff_datetime\": \"2026-02-11T22:00:00Z\",\n    \"group_code\": \"ECON\"\n  },\n  \"driver_profile\": {\n    \"driver_age\": 25, \n    \"residence_country\": \"BR\"\n  },\n  \"selections\": {\n    \"protections\": [\"TPL\"],\n    \"optionals\": [\n      { \"code\": \"GPS\", \"quantity\": 1 },\n      { \"code\": \"TOLL\", \"quantity\": 1 }\n    ]\n  },\n  \"preferences\": {\n    \"currency\": \"BRL\",\n    \"promo_code\": \"TCC_2026\"\n  }\n}\n```",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "rental_details": {
                    "type": "object",
                    "properties": {
                      "supplier_id": {
                        "type": "string",
                        "example": "localiza"
                      },
                      "pickup_store_id": {
                        "type": "string",
                        "example": "MIA"
                      },
                      "dropoff_store_id": {
                        "type": "string",
                        "example": "MIA"
                      },
                      "pickup_datetime": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "dropoff_datetime": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "group_code": {
                        "type": "string",
                        "example": "A"
                      }
                    },
                    "required": [
                      "supplier_id",
                      "pickup_store_id",
                      "dropoff_store_id",
                      "pickup_datetime",
                      "dropoff_datetime",
                      "group_code"
                    ]
                  },
                  "driver_profile": {
                    "type": "object",
                    "properties": {
                      "driver_age": {
                        "type": "integer",
                        "minimum": 16,
                        "maximum": 90
                      },
                      "residence_country": {
                        "type": "string",
                        "example": "BR"
                      }
                    },
                    "required": [
                      "residence_country"
                    ]
                  },
                  "selections": {
                    "type": "object",
                    "properties": {
                      "protections": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "example": "CDW"
                        },
                        "uniqueItems": true
                      },
                      "optionals": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "code": {
                              "type": "string",
                              "example": "CHILD_SEAT"
                            },
                            "quantity": {
                              "type": "integer"
                            }
                          },
                          "required": [
                            "code",
                            "quantity"
                          ]
                        },
                        "uniqueItems": true
                      }
                    }
                  },
                  "preferences": {
                    "type": "object",
                    "properties": {
                      "currency": {
                        "type": "string"
                      },
                      "promo_code": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "currency"
                    ]
                  }
                },
                "required": [
                  "rental_details",
                  "driver_profile",
                  "preferences"
                ]
              },
              "examples": {
                "1": {
                  "value": {
                    "rental_details": {
                      "supplier_id": "localiza",
                      "pickup_store_id": "GRU",
                      "dropoff_store_id": "CEN",
                      "pickup_datetime": "2026-01-13T21:30",
                      "dropoff_datetime": "2026-02-11T22:00",
                      "group_code": "ECON"
                    },
                    "driver_profile": {
                      "driver_age": "25",
                      "residence_country": "BR"
                    },
                    "selections": {
                      "protections": [
                        "TPL"
                      ],
                      "optionals": [
                        {
                          "code": "GPS",
                          "quantity": 1
                        },
                        {
                          "code": "TOLL",
                          "quantity": 1
                        }
                      ]
                    },
                    "preferences": {
                      "currency": "BRL"
                    }
                  },
                  "summary": "Complete - No Promo"
                },
                "2": {
                  "value": {
                    "rental_details": {
                      "supplier_id": "foco",
                      "pickup_store_id": "CEN",
                      "dropoff_store_id": "CEN",
                      "pickup_datetime": "2026-07-29T18:48:19.669Z",
                      "dropoff_datetime": "2026-12-05T05:54:18.313Z",
                      "group_code": "MVMA"
                    },
                    "driver_profile": {
                      "driver_age": "18",
                      "residence_country": "US"
                    },
                    "preferences": {
                      "currency": "USD",
                      "promo_code": "95"
                    }
                  },
                  "summary": "No Extras - With Promo"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "quote_id": {
                      "type": "string",
                      "format": "uuid"
                    },
                    "expires_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "breakdown": {
                      "type": "object",
                      "properties": {
                        "base_rate": {
                          "type": "number",
                          "format": "float"
                        },
                        "optionals": {
                          "type": "number",
                          "format": "float"
                        },
                        "protections": {
                          "type": "number",
                          "format": "float"
                        },
                        "dropoff": {
                          "type": "number",
                          "format": "float"
                        },
                        "taxes": {
                          "type": "number",
                          "format": "float"
                        },
                        "grand_total": {
                          "type": "number",
                          "format": "float"
                        }
                      },
                      "required": [
                        "base_rate",
                        "optionals",
                        "protections",
                        "dropoff",
                        "taxes",
                        "grand_total"
                      ]
                    },
                    "currency": {
                      "type": "string"
                    },
                    "warnings": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "code": {
                            "type": "string"
                          },
                          "message": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": [
                    "quote_id",
                    "expires_at",
                    "breakdown",
                    "currency",
                    "warnings"
                  ]
                },
                "example": {
                  "quote_id": "3c071a1d-db86-46a7-9dc8-72ba3fbca992",
                  "expires_at": "2026-03-18T19:47:59.990Z",
                  "breakdown": {
                    "base_rate": 100,
                    "optionals": 20.5,
                    "protections": 35.5,
                    "dropoff": 130,
                    "taxes": 37,
                    "grand_total": 358
                  },
                  "currency": "BRL",
                  "warnings": [
                    {
                      "code": "YOUNG_DRIVER_FEE_MAY_APPLY",
                      "message": "A surcharge applies for drivers under 25."
                    }
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/reserve": {
      "post": {
        "summary": "Reserve",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "quote_id": {
                    "type": "string"
                  },
                  "customer": {
                    "type": "object",
                    "properties": {
                      "first_name": {
                        "type": "string"
                      },
                      "last_name": {
                        "type": "string"
                      },
                      "email": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "document_type": {
                        "type": "string"
                      },
                      "document_number": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "first_name",
                      "last_name",
                      "email",
                      "phone",
                      "document_type",
                      "document_number"
                    ]
                  },
                  "flight_details": {
                    "type": "object",
                    "properties": {
                      "airline": {
                        "type": "string"
                      },
                      "flight_number": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "airline",
                      "flight_number"
                    ]
                  },
                  "payment": {
                    "type": "object",
                    "properties": {
                      "method": {
                        "type": "string"
                      },
                      "card_token": {
                        "type": "string"
                      },
                      "billing_address": {
                        "type": "object",
                        "properties": {
                          "street": {
                            "type": "string"
                          },
                          "city": {
                            "type": "string"
                          },
                          "country": {
                            "type": "string"
                          },
                          "postal_code": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "street",
                          "city",
                          "country",
                          "postal_code"
                        ]
                      }
                    },
                    "required": [
                      "method",
                      "card_token",
                      "billing_address"
                    ]
                  }
                },
                "required": [
                  "quote_id",
                  "customer",
                  "payment"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "reservation_id": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    },
                    "quote_id": {
                      "type": "string"
                    },
                    "customer_email": {
                      "type": "string"
                    },
                    "grand_total": {
                      "type": "number"
                    },
                    "currency": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "reservation_id",
                    "status",
                    "quote_id",
                    "customer_email",
                    "grand_total",
                    "currency",
                    "created_at"
                  ]
                },
                "example": {
                  "reservation_id": "RES-882910-BR",
                  "status": "CONFIRMED",
                  "quote_id": "a1b2c3d4-e5f6-7890-1234-56789abcdef0",
                  "customer_email": "victor@example.com",
                  "grand_total": 450.5,
                  "currency": "BRL",
                  "created_at": "2026-03-24T10:00:00Z"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}